In [29]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [30]:
#Load Cleansed Data
df_analysis_InternationalRestrictions = pd.read_csv('/content/Cleansed_Data.csv')

In [31]:
#Transform InternationalRestrictions Info
df_analysis_InternationalRestrictions.loc[df_analysis_InternationalRestrictions['InternationalRestrictions'] == 0, 'InternationalRestrictionsDetail'] = 'No_Measure'
df_analysis_InternationalRestrictions.loc[df_analysis_InternationalRestrictions['InternationalRestrictions'] == 1, 'InternationalRestrictionsDetail'] = 'Screening_Arrivals'
df_analysis_InternationalRestrictions.loc[df_analysis_InternationalRestrictions['InternationalRestrictions'] == 2, 'InternationalRestrictionsDetail'] = 'Quarantine_Arrivals_Few'
df_analysis_InternationalRestrictions.loc[df_analysis_InternationalRestrictions['InternationalRestrictions'] == 3, 'InternationalRestrictionsDetail'] = 'Ban_Arrivals_Few'
df_analysis_InternationalRestrictions.loc[df_analysis_InternationalRestrictions['InternationalRestrictions'] == 4, 'InternationalRestrictionsDetail'] = 'Ban_Arrivals_All'

In [32]:
df_analysis_InternationalRestrictions['Date'] = pd.to_datetime(df_analysis_InternationalRestrictions.Date, format= '%Y-%m-%d')
df_analysis_InternationalRestrictions['Month'] = df_analysis_InternationalRestrictions['Date'].dt.strftime("%m")
df_analysis_InternationalRestrictions['Week_Number'] = df_analysis_InternationalRestrictions['Date'].dt.isocalendar().week

In [33]:
#Find Daily Case Using Shift()
df_analysis_InternationalRestrictions['Lagged_Confirmed_Case'] = df_analysis_InternationalRestrictions.groupby(['Country', 'State'])['ConfirmedCases'].shift(1)
df_analysis_InternationalRestrictions['Daily_New_Cases'] = df_analysis_InternationalRestrictions['ConfirmedCases'] - df_analysis_InternationalRestrictions['Lagged_Confirmed_Case']

In [34]:
#Select Specific Columns
df_analysis_InternationalRestrictions = df_analysis_InternationalRestrictions[[
    'Country', 'State', 'Date', 'InternationalRestrictions', 'InternationalRestrictionsDetail', 'ConfirmedCases', 'Daily_New_Cases', 'Month', 'Week_Number'
]]

In [35]:
#Find Max Confirmed Cases per State and Save to CSV
df_MaxCases_Per_State = df_analysis_InternationalRestrictions.groupby('State')['ConfirmedCases'].max().reset_index().rename(columns= {'Daily_New_Cases':'Weekly_Cases'}).sort_values(by=['ConfirmedCases'], ascending= False)
df_MaxCases_Per_State['Rank'] = df_MaxCases_Per_State['ConfirmedCases'].rank(ascending= False)
df_MaxCases_Per_State.to_csv(r"MaxConfirmedCasesPerState.csv", index= False)

In [47]:
df_Wisconsin = df_analysis_InternationalRestrictions[df_analysis_InternationalRestrictions['State'] == "Wisconsin"]
df_Wisconsin= df_Wisconsin[[
    'Country',
    'State',
    'InternationalRestrictionsDetail',
    'Daily_New_Cases',
    'Month',
    'Week_Number'
]]
df_Wisconsin.groupby(['State', 'InternationalRestrictionsDetail', 'Month', 'Week_Number'])['Daily_New_Cases'].sum().reset_index().rename(columns= {'Daily_New_Cases':'Weekly_Cases'}).rename(columns= {'Daily_New_Cases':'Weekly_Cases'}).sort_values(by=['Month', 'Week_Number'], ascending = True)

        State InternationalRestrictionsDetail Month  Week_Number  Weekly_Cases
0   Wisconsin                Ban_Arrivals_Few    03            9           0.0
1   Wisconsin                Ban_Arrivals_Few    03           10           0.0
2   Wisconsin                Ban_Arrivals_Few    03           11          28.0
3   Wisconsin                Ban_Arrivals_Few    03           12         353.0
4   Wisconsin                Ban_Arrivals_Few    03           13         783.0
5   Wisconsin                Ban_Arrivals_Few    03           14         248.0
6   Wisconsin                Ban_Arrivals_Few    04           14         908.0
7   Wisconsin                Ban_Arrivals_Few    04           15        1021.0
8   Wisconsin                Ban_Arrivals_Few    04           16        1005.0
9   Wisconsin                Ban_Arrivals_Few    04           17        1566.0
10  Wisconsin                Ban_Arrivals_Few    04           18         942.0
11  Wisconsin                Ban_Arrivals_Few    05           18        1110.0
12  Wisconsin                Ban_Arrivals_Few    05           19        2255.0
13  Wisconsin                Ban_Arrivals_Few    05           20        2324.0
14  Wisconsin                Ban_Arrivals_Few    05           21        2734.0
15  Wisconsin                Ban_Arrivals_Few    05           22        3126.0
16  Wisconsin                Ban_Arrivals_Few    06           23        2432.0
17  Wisconsin                Ban_Arrivals_Few    06           24        1923.0
18  Wisconsin                Ban_Arrivals_Few    06           25        2061.0
19  Wisconsin                Ban_Arrivals_Few    06           26        2924.0
20  Wisconsin                Ban_Arrivals_Few    06           27         916.0
21  Wisconsin                Ban_Arrivals_Few    07           27        2918.0
22  Wisconsin                Ban_Arrivals_Few    07           28        4871.0
23  Wisconsin                Ban_Arrivals_Few    07           29        5867.0
24  Wisconsin                Ban_Arrivals_Few    07           30        6512.0
25  Wisconsin                Ban_Arrivals_Few    07           31        4113.0
26  Wisconsin                Ban_Arrivals_Few    08           31        1984.0
27  Wisconsin                Ban_Arrivals_Few    08           32        5630.0
28  Wisconsin                Ban_Arrivals_Few    08           33        5187.0
29  Wisconsin                Ban_Arrivals_Few    08           34        4721.0
30  Wisconsin                Ban_Arrivals_Few    08           35        4875.0
31  Wisconsin                Ban_Arrivals_Few    08           36         266.0
32  Wisconsin                Ban_Arrivals_Few    09           36        5590.0
33  Wisconsin                Ban_Arrivals_Few    09           37        7992.0
34  Wisconsin                Ban_Arrivals_Few    09           38       12042.0
35  Wisconsin                Ban_Arrivals_Few    09           39       14635.0
36  Wisconsin                Ban_Arrivals_Few    09           40        6412.0
37  Wisconsin                Ban_Arrivals_Few    10           40       10389.0
38  Wisconsin                Ban_Arrivals_Few    10           41       17573.0
39  Wisconsin                Ban_Arrivals_Few    10           42       15950.0
40  Wisconsin                Ban_Arrivals_Few    10           43       42731.0
41  Wisconsin                Ban_Arrivals_Few    10           44       28952.0
42  Wisconsin                Ban_Arrivals_Few    11           44        3553.0
43  Wisconsin                Ban_Arrivals_Few    11           45       40488.0
44  Wisconsin                Ban_Arrivals_Few    11           46       48014.0
45  Wisconsin                Ban_Arrivals_Few    11           47       46314.0
46  Wisconsin                Ban_Arrivals_Few    11           48       32816.0
47  Wisconsin                Ban_Arrivals_Few    11           49        2676.0

In [49]:
df_Washington = df_analysis_InternationalRestrictions[df_analysis_InternationalRestrictions['State'] == "Washington"]
df_Washington= df_Washington[[
    'Country',
    'State',
    'InternationalRestrictionsDetail',
    'Daily_New_Cases',
    'Month',
    'Week_Number'
]]
df_Washington.groupby(['State', 'InternationalRestrictionsDetail', 'Month', 'Week_Number'])['Daily_New_Cases'].sum().reset_index().rename(columns= {'Daily_New_Cases':'Weekly_Cases'}).sort_values(by=['Month', 'Week_Number'], ascending = True)

,State,InternationalRestrictionsDetail,Month,Week_Number,Weekly_Cases
0,Washington,Ban_Arrivals_Few,03,9,0.0
1,Washington,Ban_Arrivals_Few,03,10,111.0
2,Washington,Ban_Arrivals_Few,03,11,481.0
3,Washington,Ban_Arrivals_Few,03,12,1394.0
4,Washington,Ban_Arrivals_Few,03,13,2468.0
5,Washington,Ban_Arrivals_Few,03,14,967.0
6,Washington,Ban_Arrivals_Few,04,14,2393.0
7,Washington,Ban_Arrivals_Few,04,15,2784.0
8,Washington,Ban_Arrivals_Few,04,16,1369.0
9,Washington,Ban_Arrivals_Few,04,17,1543.0
10,Washington,Ban_Arrivals_Few,04,18,806.0
11,Washington,Ban_Arrivals_Few,05,18,858.0
12,Washington,Ban_Arrivals_Few,05,19,1706.0
13,Washington,Ban_Arrivals_Few,05,20,1542.0
14,Washington,Ban_Arrivals_Few,05,21,1395.0
15,Washington,Ban_Arrivals_Few,05,22,1874.0
16,Washington,Ban_Arrivals_Few,06,23,2376.0
17,Washington,Ban_Arrivals_Few,06,24,2080.0
18,Washington,Ban_Arrivals_Few,06,25,2716.0
19,Washington,Ban_Arrivals_Few,06,26,3393.0
20,Washington,Ban_Arrivals_Few,06,27,1172.0
21,Washington,Ban_Arrivals_Few,07,27,3520.0
22,Washington,Ban_Arrivals_Few,07,28,4790.0
23,Washington,Ban_Arrivals_Few,07,29,6002.0
24,Washington,Ban_Arrivals_Few,07,30,5588.0
25,Washington,Ban_Arrivals_Few,07,31,4247.0
26,Washington,Ban_Arrivals_Few,08,31,1181.0
27,Washington,Ban_Arrivals_Few,08,32,5002.0
28,Washington,Ban_Arrivals_Few,08,33,4085.0
29,Washington,Ban_Arrivals_Few,08,34,3960.0
30,Washington,Ban_Arrivals_Few,08,35,3381.0
31,Washington,Ban_Arrivals_Few,08,36,307.0
32,Washington,Ban_Arrivals_Few,09,36,2793.0
33,Washington,Ban_Arrivals_Few,09,37,2761.0
34,Washington,Ban_Arrivals_Few,09,38,2869.0
35,Washington,Ban_Arrivals_Few,09,39,3972.0
36,Washington,Ban_Arrivals_Few,09,40,1566.0
37,Washington,Ban_Arrivals_Few,10,40,2246.0
38,Washington,Ban_Arrivals_Few,10,41,4205.0
39,Washington,Ban_Arrivals_Few,10,42,4658.0
40,Washington,Ban_Arrivals_Few,10,43,5093.0
41,Washington,Ban_Arrivals_Few,10,44,5143.0
42,Washington,Ban_Arrivals_Few,11,44,1040.0
43,Washington,Ban_Arrivals_Few,11,45,9619.0
44,Washington,Ban_Arrivals_Few,11,46,13502.0
45,Washington,Ban_Arrivals_Few,11,47,16519.0
46,Washington,Ban_Arrivals_Few,11,48,18012.0
47,Washington,Ban_Arrivals_Few,11,49,2462.0

In [50]:
df_NewJersey = df_analysis_InternationalRestrictions[df_analysis_InternationalRestrictions['State'] == "New Jersey"]
df_NewJersey= df_NewJersey[[
    'Country',
    'State',
    'InternationalRestrictionsDetail',
    'Daily_New_Cases',
    'Month',
    'Week_Number'
]]
df_NewJersey.groupby(['State', 'InternationalRestrictionsDetail', 'Month', 'Week_Number'])['Daily_New_Cases'].sum().reset_index().rename(columns= {'Daily_New_Cases':'Weekly_Cases'}).sort_values(by=['Month', 'Week_Number'], ascending = True)

,State,InternationalRestrictionsDetail,Month,Week_Number,Weekly_Cases
0,New Jersey,Ban_Arrivals_Few,03,9,0.0
1,New Jersey,Ban_Arrivals_Few,03,10,5.0
2,New Jersey,Ban_Arrivals_Few,03,11,67.0
3,New Jersey,Ban_Arrivals_Few,03,12,1842.0
4,New Jersey,Ban_Arrivals_Few,03,13,11472.0
5,New Jersey,Ban_Arrivals_Few,03,14,5310.0
6,New Jersey,Ban_Arrivals_Few,04,14,18809.0
7,New Jersey,Ban_Arrivals_Few,04,15,24345.0
8,New Jersey,Ban_Arrivals_Few,04,16,23451.0
9,New Jersey,Ban_Arrivals_Few,04,17,23737.0
10,New Jersey,Ban_Arrivals_Few,04,18,9614.0
11,New Jersey,Ban_Arrivals_Few,05,18,8111.0
12,New Jersey,Ban_Arrivals_Few,05,19,12060.0
13,New Jersey,Ban_Arrivals_Few,05,20,7830.0
14,New Jersey,Ban_Arrivals_Few,05,21,7749.0
15,New Jersey,Ban_Arrivals_Few,05,22,6358.0
16,New Jersey,Ban_Arrivals_Few,06,23,3833.0
17,New Jersey,Ban_Arrivals_Few,06,24,2832.0
18,New Jersey,Ban_Arrivals_Few,06,25,2418.0
19,New Jersey,Ban_Arrivals_Few,06,26,2223.0
20,New Jersey,Ban_Arrivals_Few,06,27,567.0
21,New Jersey,Ban_Arrivals_Few,07,27,1891.0
22,New Jersey,Ban_Arrivals_Few,07,28,2184.0
23,New Jersey,Ban_Arrivals_Few,07,29,1807.0
24,New Jersey,Ban_Arrivals_Few,07,30,2900.0
25,New Jersey,Ban_Arrivals_Few,07,31,2538.0
26,New Jersey,Ban_Arrivals_Few,08,31,756.0
27,New Jersey,Ban_Arrivals_Few,08,32,2690.0
28,New Jersey,Ban_Arrivals_Few,08,33,2973.0
29,New Jersey,Ban_Arrivals_Few,08,34,2319.0
30,New Jersey,Ban_Arrivals_Few,08,35,2407.0
31,New Jersey,Ban_Arrivals_Few,08,36,402.0
32,New Jersey,Ban_Arrivals_Few,09,36,2371.0
33,New Jersey,Ban_Arrivals_Few,09,37,2924.0
34,New Jersey,Ban_Arrivals_Few,09,38,3496.0
35,New Jersey,Ban_Arrivals_Few,09,39,4326.0
36,New Jersey,Ban_Arrivals_Few,09,40,2044.0
37,New Jersey,Ban_Arrivals_Few,10,40,3273.0
38,New Jersey,Ban_Arrivals_Few,10,41,6177.0
39,New Jersey,Ban_Arrivals_Few,10,42,7359.0
40,New Jersey,Ban_Arrivals_Few,10,43,10773.0
41,New Jersey,Ban_Arrivals_Few,10,44,11847.0
42,New Jersey,Ban_Arrivals_Few,11,44,2173.0
43,New Jersey,Ban_Arrivals_Few,11,45,18983.0
44,New Jersey,Ban_Arrivals_Few,11,46,29037.0
45,New Jersey,Ban_Arrivals_Few,11,47,31111.0
46,New Jersey,Ban_Arrivals_Few,11,48,32653.0
47,New Jersey,Ban_Arrivals_Few,11,49,4039.0

In [51]:
df_Oregon = df_analysis_InternationalRestrictions[df_analysis_InternationalRestrictions['State'] == "Oregon"]
df_Oregon= df_Oregon[[
    'Country',
    'State',
    'InternationalRestrictionsDetail',
    'Daily_New_Cases',
    'Month',
    'Week_Number'
]]
df_Oregon.groupby(['State', 'InternationalRestrictionsDetail', 'Month', 'Week_Number'])['Daily_New_Cases'].sum().reset_index().rename(columns= {'Daily_New_Cases':'Weekly_Cases'}).sort_values(by=['Month', 'Week_Number'], ascending = True)

     State InternationalRestrictionsDetail Month  Week_Number  Weekly_Cases
0   Oregon                Ban_Arrivals_Few    03            9           0.0
1   Oregon                Ban_Arrivals_Few    03           10          13.0
2   Oregon                Ban_Arrivals_Few    03           11          22.0
3   Oregon                Ban_Arrivals_Few    03           12         125.0
4   Oregon                Ban_Arrivals_Few    03           13         387.0
5   Oregon                Ban_Arrivals_Few    03           14         142.0
6   Oregon                Ban_Arrivals_Few    04           14         378.0
7   Oregon                Ban_Arrivals_Few    04           15         459.0
8   Oregon                Ban_Arrivals_Few    04           16         383.0
9   Oregon                Ban_Arrivals_Few    04           17         401.0
10  Oregon                Ban_Arrivals_Few    04           18         199.0
11  Oregon                Ban_Arrivals_Few    05           18         170.0
12  Oregon                Ban_Arrivals_Few    05           19         548.0
13  Oregon                Ban_Arrivals_Few    05           20         395.0
14  Oregon                Ban_Arrivals_Few    05           21         304.0
15  Oregon                Ban_Arrivals_Few    05           22         316.0
16  Oregon                Ban_Arrivals_Few    06           23         419.0
17  Oregon                Ban_Arrivals_Few    06           24         974.0
18  Oregon                Ban_Arrivals_Few    06           25        1301.0
19  Oregon                Ban_Arrivals_Few    06           26        1404.0
20  Oregon                Ban_Arrivals_Few    06           27         315.0
21  Oregon                Ban_Arrivals_Few    07           27        1574.0
22  Oregon                Ban_Arrivals_Few    07           28        1940.0
23  Oregon                Ban_Arrivals_Few    07           29        2409.0
24  Oregon                Ban_Arrivals_Few    07           30        2179.0
25  Oregon                Ban_Arrivals_Few    07           31        1734.0
26  Oregon                Ban_Arrivals_Few    08           31         605.0
27  Oregon                Ban_Arrivals_Few    08           32        2175.0
28  Oregon                Ban_Arrivals_Few    08           33        1990.0
29  Oregon                Ban_Arrivals_Few    08           34        1675.0
30  Oregon                Ban_Arrivals_Few    08           35        1617.0
31  Oregon                Ban_Arrivals_Few    08           36         159.0
32  Oregon                Ban_Arrivals_Few    09           36        1331.0
33  Oregon                Ban_Arrivals_Few    09           37        1293.0
34  Oregon                Ban_Arrivals_Few    09           38        1464.0
35  Oregon                Ban_Arrivals_Few    09           39        2019.0
36  Oregon                Ban_Arrivals_Few    09           40         689.0
37  Oregon                Ban_Arrivals_Few    10           40        1261.0
38  Oregon                Ban_Arrivals_Few    10           41        2485.0
39  Oregon                Ban_Arrivals_Few    10           42        2277.0
40  Oregon                Ban_Arrivals_Few    10           43        2569.0
41  Oregon                Ban_Arrivals_Few    10           44        2820.0
42  Oregon                Ban_Arrivals_Few    11           44         508.0
43  Oregon                Ban_Arrivals_Few    11           45        5019.0
44  Oregon                Ban_Arrivals_Few    11           46        6432.0
45  Oregon                Ban_Arrivals_Few    11           47        8290.0
46  Oregon                Ban_Arrivals_Few    11           48        8949.0
47  Oregon                Ban_Arrivals_Few    11           49        1312.0

In [52]:
df_Tennessee = df_analysis_InternationalRestrictions[df_analysis_InternationalRestrictions['State'] == "Tennessee"]
df_Tennessee= df_Tennessee[[
    'Country',
    'State',
    'InternationalRestrictionsDetail',
    'Daily_New_Cases',
    'Month',
    'Week_Number'
]]
df_Tennessee.groupby(['State', 'InternationalRestrictionsDetail', 'Month', 'Week_Number'])['Daily_New_Cases'].sum().reset_index().rename(columns= {'Daily_New_Cases':'Weekly_Cases'}).sort_values(by=['Month', 'Week_Number'], ascending = True)

        State InternationalRestrictionsDetail Month  Week_Number  Weekly_Cases
0   Tennessee                Ban_Arrivals_Few    03            9           0.0
1   Tennessee                Ban_Arrivals_Few    03           10           3.0
2   Tennessee                Ban_Arrivals_Few    03           11          29.0
3   Tennessee                Ban_Arrivals_Few    03           12         361.0
4   Tennessee                Ban_Arrivals_Few    03           13        1327.0
5   Tennessee                Ban_Arrivals_Few    03           14         671.0
6   Tennessee                Ban_Arrivals_Few    04           14        1269.0
7   Tennessee                Ban_Arrivals_Few    04           15        1730.0
8   Tennessee                Ban_Arrivals_Few    04           16        1721.0
9   Tennessee                Ban_Arrivals_Few    04           17        2556.0
10  Tennessee                Ban_Arrivals_Few    04           18        2140.0
11  Tennessee                Ban_Arrivals_Few    05           18        1376.0
12  Tennessee                Ban_Arrivals_Few    05           19        1836.0
13  Tennessee                Ban_Arrivals_Few    05           20        2753.0
14  Tennessee                Ban_Arrivals_Few    05           21        2451.0
15  Tennessee                Ban_Arrivals_Few    05           22        3051.0
16  Tennessee                Ban_Arrivals_Few    06           23        3231.0
17  Tennessee                Ban_Arrivals_Few    06           24        3795.0
18  Tennessee                Ban_Arrivals_Few    06           25        4546.0
19  Tennessee                Ban_Arrivals_Few    06           26        5433.0
20  Tennessee                Ban_Arrivals_Few    06           27        3417.0
21  Tennessee                Ban_Arrivals_Few    07           27        7461.0
22  Tennessee                Ban_Arrivals_Few    07           28       11916.0
23  Tennessee                Ban_Arrivals_Few    07           29       14584.0
24  Tennessee                Ban_Arrivals_Few    07           30       16033.0
25  Tennessee                Ban_Arrivals_Few    07           31       10850.0
26  Tennessee                Ban_Arrivals_Few    08           31        3221.0
27  Tennessee                Ban_Arrivals_Few    08           32       13023.0
28  Tennessee                Ban_Arrivals_Few    08           33       11120.0
29  Tennessee                Ban_Arrivals_Few    08           34       10112.0
30  Tennessee                Ban_Arrivals_Few    08           35       10083.0
31  Tennessee                Ban_Arrivals_Few    08           36        1237.0
32  Tennessee                Ban_Arrivals_Few    09           36        8997.0
33  Tennessee                Ban_Arrivals_Few    09           37        8435.0
34  Tennessee                Ban_Arrivals_Few    09           38       11002.0
35  Tennessee                Ban_Arrivals_Few    09           39        9414.0
36  Tennessee                Ban_Arrivals_Few    09           40        3280.0
37  Tennessee                Ban_Arrivals_Few    10           40        5488.0
38  Tennessee                Ban_Arrivals_Few    10           41       14225.0
39  Tennessee                Ban_Arrivals_Few    10           42       13451.0
40  Tennessee                Ban_Arrivals_Few    10           43       18293.0
41  Tennessee                Ban_Arrivals_Few    10           44       11476.0
42  Tennessee                Ban_Arrivals_Few    11           44        2470.0
43  Tennessee                Ban_Arrivals_Few    11           45       21993.0
44  Tennessee                Ban_Arrivals_Few    11           46       28033.0
45  Tennessee                Ban_Arrivals_Few    11           47       28066.0
46  Tennessee                Ban_Arrivals_Few    11           48       27177.0
47  Tennessee                Ban_Arrivals_Few    11           49        5937.0

In [53]:
df_NewYork = df_analysis_InternationalRestrictions[df_analysis_InternationalRestrictions['State'] == "New York"]
df_NewYork= df_NewYork[[
    'Country',
    'State',
    'InternationalRestrictionsDetail',
    'Daily_New_Cases',
    'Month',
    'Week_Number'
]]
df_NewYork.groupby(['State', 'InternationalRestrictionsDetail', 'Month', 'Week_Number'])['Daily_New_Cases'].sum().reset_index().rename(columns= {'Daily_New_Cases':'Weekly_Cases'}).sort_values(by=['Month', 'Week_Number'], ascending = True)

       State InternationalRestrictionsDetail Month  Week_Number  Weekly_Cases
0   New York                Ban_Arrivals_Few    03            9           0.0
1   New York                Ban_Arrivals_Few    03           10         105.0
2   New York                Ban_Arrivals_Few    03           11         528.0
3   New York                Ban_Arrivals_Few    03           12       14558.0
4   New York                Ban_Arrivals_Few    03           13       44457.0
5   New York                Ban_Arrivals_Few    03           14       16205.0
6   New York                Ban_Arrivals_Few    04           14       56847.0
7   New York                Ban_Arrivals_Few    04           15       67935.0
8   New York                Ban_Arrivals_Few    04           16       50378.0
9   New York                Ban_Arrivals_Few    04           17       42562.0
10  New York                Ban_Arrivals_Few    04           18       14734.0
11  New York                Ban_Arrivals_Few    05           18       12376.0
12  New York                Ban_Arrivals_Few    05           19       18517.0
13  New York                Ban_Arrivals_Few    05           20       13800.0
14  New York                Ban_Arrivals_Few    05           21       11695.0
15  New York                Ban_Arrivals_Few    05           22        8985.0
16  New York                Ban_Arrivals_Few    06           23        7241.0
17  New York                Ban_Arrivals_Few    06           24        4874.0
18  New York                Ban_Arrivals_Few    06           25        4471.0
19  New York                Ban_Arrivals_Few    06           26        4604.0
20  New York                Ban_Arrivals_Few    06           27        1037.0
21  New York                Ban_Arrivals_Few    07           27        3867.0
22  New York                Ban_Arrivals_Few    07           28        4848.0
23  New York                Ban_Arrivals_Few    07           29        5400.0
24  New York                Ban_Arrivals_Few    07           30        4921.0
25  New York                Ban_Arrivals_Few    07           31        3199.0
26  New York                Ban_Arrivals_Few    08           31        1308.0
27  New York                Ban_Arrivals_Few    08           32        4299.0
28  New York                Ban_Arrivals_Few    08           33        4161.0
29  New York                Ban_Arrivals_Few    08           34        4173.0
30  New York                Ban_Arrivals_Few    08           35        4384.0
31  New York                Ban_Arrivals_Few    08           36         685.0
32  New York                Ban_Arrivals_Few    09           36        4594.0
33  New York                Ban_Arrivals_Few    09           37        5114.0
34  New York                Ban_Arrivals_Few    09           38        5645.0
35  New York                Ban_Arrivals_Few    09           39        6098.0
36  New York                Ban_Arrivals_Few    09           40        2932.0
37  New York                Ban_Arrivals_Few    10           40        6156.0
38  New York                Ban_Arrivals_Few    10           41        9978.0
39  New York                Ban_Arrivals_Few    10           42       10048.0
40  New York                Ban_Arrivals_Few    10           43       11933.0
41  New York                Ban_Arrivals_Few    10           44       12109.0
42  New York                Ban_Arrivals_Few    11           44        2122.0
43  New York                Ban_Arrivals_Few    11           45       19914.0
44  New York                Ban_Arrivals_Few    11           46       32316.0
45  New York                Ban_Arrivals_Few    11           47       37247.0
46  New York                Ban_Arrivals_Few    11           48       45281.0
47  New York                Ban_Arrivals_Few    11           49        7772.0

In [54]:
df_Texas = df_analysis_InternationalRestrictions[df_analysis_InternationalRestrictions['State'] == "Texas"]
df_Texas= df_Texas[[
    'Country',
    'State',
    'InternationalRestrictionsDetail',
    'Daily_New_Cases',
    'Month',
    'Week_Number'
]]
df_Texas.groupby(['State', 'InternationalRestrictionsDetail', 'Month', 'Week_Number'])['Daily_New_Cases'].sum().reset_index().rename(columns= {'Daily_New_Cases':'Weekly_Cases'}).sort_values(by=['Month', 'Week_Number'], ascending = True)

    State InternationalRestrictionsDetail Month  Week_Number  Weekly_Cases
0   Texas                Ban_Arrivals_Few    03            9           0.0
1   Texas                Ban_Arrivals_Few    03           10          11.0
2   Texas                Ban_Arrivals_Few    03           11          53.0
3   Texas                Ban_Arrivals_Few    03           12         579.0
4   Texas                Ban_Arrivals_Few    03           13        2149.0
5   Texas                Ban_Arrivals_Few    03           14        1017.0
6   Texas                Ban_Arrivals_Few    04           14        1595.0
7   Texas                Ban_Arrivals_Few    04           15        4393.0
8   Texas                Ban_Arrivals_Few    04           16        3977.0
9   Texas                Ban_Arrivals_Few    04           17        5006.0
10  Texas                Ban_Arrivals_Few    04           18        4663.0
11  Texas                Ban_Arrivals_Few    05           18        2361.0
12  Texas                Ban_Arrivals_Few    05           19        8063.0
13  Texas                Ban_Arrivals_Few    05           20        6948.0
14  Texas                Ban_Arrivals_Few    05           21        6419.0
15  Texas                Ban_Arrivals_Few    05           22        6464.0
16  Texas                Ban_Arrivals_Few    06           23       16354.0
17  Texas                Ban_Arrivals_Few    06           24       15153.0
18  Texas                Ban_Arrivals_Few    06           25       25498.0
19  Texas                Ban_Arrivals_Few    06           26       39688.0
20  Texas                Ban_Arrivals_Few    06           27       15763.0
21  Texas                Ban_Arrivals_Few    07           27       30839.0
22  Texas                Ban_Arrivals_Few    07           28       60737.0
23  Texas                Ban_Arrivals_Few    07           29       59930.0
24  Texas                Ban_Arrivals_Few    07           30       56549.0
25  Texas                Ban_Arrivals_Few    07           31       45029.0
26  Texas                Ban_Arrivals_Few    08           31        9325.0
27  Texas                Ban_Arrivals_Few    08           32       76848.0
28  Texas                Ban_Arrivals_Few    08           33       68196.0
29  Texas                Ban_Arrivals_Few    08           34       42116.0
30  Texas                Ban_Arrivals_Few    08           35       34706.0
31  Texas                Ban_Arrivals_Few    08           36        4585.0
32  Texas                Ban_Arrivals_Few    09           36       20981.0
33  Texas                Ban_Arrivals_Few    09           37       34131.0
34  Texas                Ban_Arrivals_Few    09           38       35518.0
35  Texas                Ban_Arrivals_Few    09           39       24593.0
36  Texas                Ban_Arrivals_Few    09           40       14718.0
37  Texas                Ban_Arrivals_Few    10           40       12846.0
38  Texas                Ban_Arrivals_Few    10           41       23356.0
39  Texas                Ban_Arrivals_Few    10           42       33065.0
40  Texas                Ban_Arrivals_Few    10           43       33964.0
41  Texas                Ban_Arrivals_Few    10           44       45081.0
42  Texas                Ban_Arrivals_Few    11           44        3577.0
43  Texas                Ban_Arrivals_Few    11           45       49775.0
44  Texas                Ban_Arrivals_Few    11           46       59986.0
45  Texas                Ban_Arrivals_Few    11           47       79630.0
46  Texas                Ban_Arrivals_Few    11           48       99174.0
47  Texas                Ban_Arrivals_Few    11           49       11780.0

In [55]:
df_Arizona = df_analysis_InternationalRestrictions[df_analysis_InternationalRestrictions['State'] == "Arizona"]
df_Arizona= df_Arizona[[
    'Country',
    'State',
    'InternationalRestrictionsDetail',
    'Daily_New_Cases',
    'Month',
    'Week_Number'
]]
df_Arizona.groupby(['State', 'InternationalRestrictionsDetail', 'Month', 'Week_Number'])['Daily_New_Cases'].sum().reset_index().rename(columns= {'Daily_New_Cases':'Weekly_Cases'}).sort_values(by=['Month', 'Week_Number'], ascending = True)

      State InternationalRestrictionsDetail Month  Week_Number  Weekly_Cases
0   Arizona                Ban_Arrivals_Few    03            9           0.0
1   Arizona                Ban_Arrivals_Few    03           10           3.0
2   Arizona                Ban_Arrivals_Few    03           11           8.0
3   Arizona                Ban_Arrivals_Few    03           12         140.0
4   Arizona                Ban_Arrivals_Few    03           13         767.0
5   Arizona                Ban_Arrivals_Few    03           14         370.0
6   Arizona                Ban_Arrivals_Few    04           14         980.0
7   Arizona                Ban_Arrivals_Few    04           15        1273.0
8   Arizona                Ban_Arrivals_Few    04           16        1391.0
9   Arizona                Ban_Arrivals_Few    04           17        1601.0
10  Arizona                Ban_Arrivals_Few    04           18        1121.0
11  Arizona                Ban_Arrivals_Few    05           18         985.0
12  Arizona                Ban_Arrivals_Few    05           19        2479.0
13  Arizona                Ban_Arrivals_Few    05           20        2826.0
14  Arizona                Ban_Arrivals_Few    05           21        2432.0
15  Arizona                Ban_Arrivals_Few    05           22        3559.0
16  Arizona                Ban_Arrivals_Few    06           23        7053.0
17  Arizona                Ban_Arrivals_Few    06           24        8717.0
18  Arizona                Ban_Arrivals_Few    06           25       16885.0
19  Arizona                Ban_Arrivals_Few    06           26       21329.0
20  Arizona                Ban_Arrivals_Few    06           27        5308.0
21  Arizona                Ban_Arrivals_Few    07           27       18875.0
22  Arizona                Ban_Arrivals_Few    07           28       24364.0
23  Arizona                Ban_Arrivals_Few    07           29       21157.0
24  Arizona                Ban_Arrivals_Few    07           30       18390.0
25  Arizona                Ban_Arrivals_Few    07           31       11996.0
26  Arizona                Ban_Arrivals_Few    08           31        4457.0
27  Arizona                Ban_Arrivals_Few    08           32        8456.0
28  Arizona                Ban_Arrivals_Few    08           33        6614.0
29  Arizona                Ban_Arrivals_Few    08           34        4566.0
30  Arizona                Ban_Arrivals_Few    08           35        3558.0
31  Arizona                Ban_Arrivals_Few    08           36         174.0
32  Arizona                Ban_Arrivals_Few    09           36        3932.0
33  Arizona                Ban_Arrivals_Few    09           37        2745.0
34  Arizona                Ban_Arrivals_Few    09           38        5509.0
35  Arizona                Ban_Arrivals_Few    09           39        3216.0
36  Arizona                Ban_Arrivals_Few    09           40        1270.0
37  Arizona                Ban_Arrivals_Few    10           40        2247.0
38  Arizona                Ban_Arrivals_Few    10           41        4821.0
39  Arizona                Ban_Arrivals_Few    10           42        5574.0
40  Arizona                Ban_Arrivals_Few    10           43        7014.0
41  Arizona                Ban_Arrivals_Few    10           44        7783.0
42  Arizona                Ban_Arrivals_Few    11           44        1527.0
43  Arizona                Ban_Arrivals_Few    11           45       11791.0
44  Arizona                Ban_Arrivals_Few    11           46       16172.0
45  Arizona                Ban_Arrivals_Few    11           47       24229.0
46  Arizona                Ban_Arrivals_Few    11           48       26330.0
47  Arizona                Ban_Arrivals_Few    11           49         822.0

In [56]:
df_RhodeIsland = df_analysis_InternationalRestrictions[df_analysis_InternationalRestrictions['State'] == "Rhode Island"]
df_RhodeIsland= df_RhodeIsland[[
    'Country',
    'State',
    'InternationalRestrictionsDetail',
    'Daily_New_Cases',
    'Month',
    'Week_Number'
]]
df_RhodeIsland.groupby(['State', 'InternationalRestrictionsDetail', 'Month', 'Week_Number'])['Daily_New_Cases'].sum().reset_index().rename(columns= {'Daily_New_Cases':'Weekly_Cases'}).sort_values(by=['Month', 'Week_Number'], ascending = True)

,State,InternationalRestrictionsDetail,Month,Week_Number,Weekly_Cases
0,Rhode Island,Ban_Arrivals_Few,03,9,0.0
1,Rhode Island,Ban_Arrivals_Few,03,10,2.0
2,Rhode Island,Ban_Arrivals_Few,03,11,17.0
3,Rhode Island,Ban_Arrivals_Few,03,12,63.0
4,Rhode Island,Ban_Arrivals_Few,03,13,211.0
5,Rhode Island,Ban_Arrivals_Few,03,14,194.0
6,Rhode Island,Ban_Arrivals_Few,04,14,434.0
7,Rhode Island,Ban_Arrivals_Few,04,15,1743.0
8,Rhode Island,Ban_Arrivals_Few,04,16,2041.0
9,Rhode Island,Ban_Arrivals_Few,04,17,2733.0
10,Rhode Island,Ban_Arrivals_Few,04,18,1182.0
11,Rhode Island,Ban_Arrivals_Few,05,18,856.0
12,Rhode Island,Ban_Arrivals_Few,05,19,1797.0
13,Rhode Island,Ban_Arrivals_Few,05,20,1400.0
14,Rhode Island,Ban_Arrivals_Few,05,21,1391.0
15,Rhode Island,Ban_Arrivals_Few,05,22,863.0
16,Rhode Island,Ban_Arrivals_Few,06,23,513.0
17,Rhode Island,Ban_Arrivals_Few,06,24,506.0
18,Rhode Island,Ban_Arrivals_Few,06,25,390.0
19,Rhode Island,Ban_Arrivals_Few,06,26,324.0
20,Rhode Island,Ban_Arrivals_Few,06,27,152.0
21,Rhode Island,Ban_Arrivals_Few,07,27,178.0
22,Rhode Island,Ban_Arrivals_Few,07,28,321.0
23,Rhode Island,Ban_Arrivals_Few,07,29,481.0
24,Rhode Island,Ban_Arrivals_Few,07,30,431.0
25,Rhode Island,Ban_Arrivals_Few,07,31,798.0
26,Rhode Island,Ban_Arrivals_Few,08,31,0.0
27,Rhode Island,Ban_Arrivals_Few,08,32,716.0
28,Rhode Island,Ban_Arrivals_Few,08,33,597.0
29,Rhode Island,Ban_Arrivals_Few,08,34,687.0
30,Rhode Island,Ban_Arrivals_Few,08,35,661.0
31,Rhode Island,Ban_Arrivals_Few,08,36,266.0
32,Rhode Island,Ban_Arrivals_Few,09,36,294.0
33,Rhode Island,Ban_Arrivals_Few,09,37,662.0
34,Rhode Island,Ban_Arrivals_Few,09,38,715.0
35,Rhode Island,Ban_Arrivals_Few,09,39,561.0
36,Rhode Island,Ban_Arrivals_Few,09,40,567.0
37,Rhode Island,Ban_Arrivals_Few,10,40,328.0
38,Rhode Island,Ban_Arrivals_Few,10,41,1218.0
39,Rhode Island,Ban_Arrivals_Few,10,42,1397.0
40,Rhode Island,Ban_Arrivals_Few,10,43,2427.0
41,Rhode Island,Ban_Arrivals_Few,10,44,2756.0
42,Rhode Island,Ban_Arrivals_Few,11,44,0.0
43,Rhode Island,Ban_Arrivals_Few,11,45,3506.0
44,Rhode Island,Ban_Arrivals_Few,11,46,5149.0
45,Rhode Island,Ban_Arrivals_Few,11,47,6472.0
46,Rhode Island,Ban_Arrivals_Few,11,48,5953.0
47,Rhode Island,Ban_Arrivals_Few,11,49,2769.0

In [57]:
df_Connecticut = df_analysis_InternationalRestrictions[df_analysis_InternationalRestrictions['State'] == "Connecticut"]
df_Connecticut= df_Connecticut[[
    'Country',
    'State',
    'InternationalRestrictionsDetail',
    'Daily_New_Cases',
    'Month',
    'Week_Number'
]]
df_Connecticut.groupby(['State', 'InternationalRestrictionsDetail', 'Month', 'Week_Number'])['Daily_New_Cases'].sum().reset_index().rename(columns= {'Daily_New_Cases':'Weekly_Cases'}).sort_values(by=['Month', 'Week_Number'], ascending = True)

,State,InternationalRestrictionsDetail,Month,Week_Number,Weekly_Cases
0,Connecticut,Ban_Arrivals_Few,03,9,0.0
1,Connecticut,Ban_Arrivals_Few,03,10,0.0
2,Connecticut,Ban_Arrivals_Few,03,11,24.0
3,Connecticut,Ban_Arrivals_Few,03,12,303.0
4,Connecticut,Ban_Arrivals_Few,03,13,1666.0
5,Connecticut,Ban_Arrivals_Few,03,14,1135.0
6,Connecticut,Ban_Arrivals_Few,04,14,2547.0
7,Connecticut,Ban_Arrivals_Few,04,15,6360.0
8,Connecticut,Ban_Arrivals_Few,04,16,5927.0
9,Connecticut,Ban_Arrivals_Few,04,17,7307.0
10,Connecticut,Ban_Arrivals_Few,04,18,2431.0
11,Connecticut,Ban_Arrivals_Few,05,18,1587.0
12,Connecticut,Ban_Arrivals_Few,05,19,4267.0
13,Connecticut,Ban_Arrivals_Few,05,20,3865.0
14,Connecticut,Ban_Arrivals_Few,05,21,3049.0
15,Connecticut,Ban_Arrivals_Few,05,22,1733.0
16,Connecticut,Ban_Arrivals_Few,06,23,1767.0
17,Connecticut,Ban_Arrivals_Few,06,24,1120.0
18,Connecticut,Ban_Arrivals_Few,06,25,667.0
19,Connecticut,Ban_Arrivals_Few,06,26,548.0
20,Connecticut,Ban_Arrivals_Few,06,27,211.0
21,Connecticut,Ban_Arrivals_Few,07,27,203.0
22,Connecticut,Ban_Arrivals_Few,07,28,570.0
23,Connecticut,Ban_Arrivals_Few,07,29,606.0
24,Connecticut,Ban_Arrivals_Few,07,30,883.0
25,Connecticut,Ban_Arrivals_Few,07,31,1034.0
26,Connecticut,Ban_Arrivals_Few,08,31,0.0
27,Connecticut,Ban_Arrivals_Few,08,32,510.0
28,Connecticut,Ban_Arrivals_Few,08,33,577.0
29,Connecticut,Ban_Arrivals_Few,08,34,622.0
30,Connecticut,Ban_Arrivals_Few,08,35,976.0
31,Connecticut,Ban_Arrivals_Few,08,36,384.0
32,Connecticut,Ban_Arrivals_Few,09,36,486.0
33,Connecticut,Ban_Arrivals_Few,09,37,961.0
34,Connecticut,Ban_Arrivals_Few,09,38,1201.0
35,Connecticut,Ban_Arrivals_Few,09,39,1060.0
36,Connecticut,Ban_Arrivals_Few,09,40,963.0
37,Connecticut,Ban_Arrivals_Few,10,40,747.0
38,Connecticut,Ban_Arrivals_Few,10,41,1741.0
39,Connecticut,Ban_Arrivals_Few,10,42,2792.0
40,Connecticut,Ban_Arrivals_Few,10,43,3222.0
41,Connecticut,Ban_Arrivals_Few,10,44,5155.0
42,Connecticut,Ban_Arrivals_Few,11,44,0.0
43,Connecticut,Ban_Arrivals_Few,11,45,6918.0
44,Connecticut,Ban_Arrivals_Few,11,46,10520.0
45,Connecticut,Ban_Arrivals_Few,11,47,12824.0
46,Connecticut,Ban_Arrivals_Few,11,48,11112.0
47,Connecticut,Ban_Arrivals_Few,11,49,4714.0

In [58]:
df_WashingtonDC = df_analysis_InternationalRestrictions[df_analysis_InternationalRestrictions['State'] == "Washington DC"]
df_WashingtonDC= df_WashingtonDC[[
    'Country',
    'State',
    'InternationalRestrictionsDetail',
    'Daily_New_Cases',
    'Month',
    'Week_Number'
]]
df_WashingtonDC.groupby(['State', 'InternationalRestrictionsDetail', 'Month', 'Week_Number'])['Daily_New_Cases'].sum().reset_index().rename(columns= {'Daily_New_Cases':'Weekly_Cases'}).sort_values(by=['Month', 'Week_Number'], ascending = True)

,State,InternationalRestrictionsDetail,Month,Week_Number,Weekly_Cases
0,Washington DC,Ban_Arrivals_Few,03,9,0.0
1,Washington DC,Ban_Arrivals_Few,03,10,0.0
2,Washington DC,Ban_Arrivals_Few,03,11,0.0
3,Washington DC,Ban_Arrivals_Few,03,12,102.0
4,Washington DC,Ban_Arrivals_Few,03,13,240.0
5,Washington DC,Ban_Arrivals_Few,03,14,153.0
6,Washington DC,Ban_Arrivals_Few,04,14,507.0
7,Washington DC,Ban_Arrivals_Few,04,15,873.0
8,Washington DC,Ban_Arrivals_Few,04,16,918.0
9,Washington DC,Ban_Arrivals_Few,04,17,1048.0
10,Washington DC,Ban_Arrivals_Few,04,18,482.0
11,Washington DC,Ban_Arrivals_Few,05,18,693.0
12,Washington DC,Ban_Arrivals_Few,05,19,1256.0
13,Washington DC,Ban_Arrivals_Few,05,20,851.0
14,Washington DC,Ban_Arrivals_Few,05,21,987.0
15,Washington DC,Ban_Arrivals_Few,05,22,691.0
16,Washington DC,Ban_Arrivals_Few,06,23,531.0
17,Washington DC,Ban_Arrivals_Few,06,24,435.0
18,Washington DC,Ban_Arrivals_Few,06,25,253.0
19,Washington DC,Ban_Arrivals_Few,06,26,228.0
20,Washington DC,Ban_Arrivals_Few,06,27,79.0
21,Washington DC,Ban_Arrivals_Few,07,27,155.0
22,Washington DC,Ban_Arrivals_Few,07,28,365.0
23,Washington DC,Ban_Arrivals_Few,07,29,414.0
24,Washington DC,Ban_Arrivals_Few,07,30,519.0
25,Washington DC,Ban_Arrivals_Few,07,31,346.0
26,Washington DC,Ban_Arrivals_Few,08,31,148.0
27,Washington DC,Ban_Arrivals_Few,08,32,479.0
28,Washington DC,Ban_Arrivals_Few,08,33,467.0
29,Washington DC,Ban_Arrivals_Few,08,34,370.0
30,Washington DC,Ban_Arrivals_Few,08,35,369.0
31,Washington DC,Ban_Arrivals_Few,08,36,33.0
32,Washington DC,Ban_Arrivals_Few,09,36,287.0
33,Washington DC,Ban_Arrivals_Few,09,37,313.0
34,Washington DC,Ban_Arrivals_Few,09,38,363.0
35,Washington DC,Ban_Arrivals_Few,09,39,295.0
36,Washington DC,Ban_Arrivals_Few,09,40,76.0
37,Washington DC,Ban_Arrivals_Few,10,40,193.0
38,Washington DC,Ban_Arrivals_Few,10,41,465.0
39,Washington DC,Ban_Arrivals_Few,10,42,386.0
40,Washington DC,Ban_Arrivals_Few,10,43,397.0
41,Washington DC,Ban_Arrivals_Few,10,44,499.0
42,Washington DC,Ban_Arrivals_Few,11,44,103.0
43,Washington DC,Ban_Arrivals_Few,11,45,632.0
44,Washington DC,Ban_Arrivals_Few,11,46,976.0
45,Washington DC,Ban_Arrivals_Few,11,47,1174.0
46,Washington DC,Ban_Arrivals_Few,11,48,1297.0
47,Washington DC,Ban_Arrivals_Few,11,49,104.0

In [59]:
df_Utah = df_analysis_InternationalRestrictions[df_analysis_InternationalRestrictions['State'] == "Utah"]
df_Utah= df_Utah[[
    'Country',
    'State',
    'InternationalRestrictionsDetail',
    'Daily_New_Cases',
    'Month',
    'Week_Number'
]]
df_Utah.groupby(['State', 'InternationalRestrictionsDetail', 'Month', 'Week_Number'])['Daily_New_Cases'].sum().reset_index().rename(columns= {'Daily_New_Cases':'Weekly_Cases'}).sort_values(by=['Month', 'Week_Number'], ascending = True)

   State InternationalRestrictionsDetail Month  Week_Number  Weekly_Cases
0   Utah                Ban_Arrivals_Few    03            9           0.0
1   Utah                Ban_Arrivals_Few    03           10           1.0
2   Utah                Ban_Arrivals_Few    03           11          17.0
3   Utah                Ban_Arrivals_Few    03           12         144.0
4   Utah                Ban_Arrivals_Few    03           13         558.0
5   Utah                Ban_Arrivals_Few    03           14         168.0
6   Utah                Ban_Arrivals_Few    04           14         713.0
7   Utah                Ban_Arrivals_Few    04           15         702.0
8   Utah                Ban_Arrivals_Few    04           16         766.0
9   Utah                Ban_Arrivals_Few    04           17        1054.0
10  Utah                Ban_Arrivals_Few    04           18         549.0
11  Utah                Ban_Arrivals_Few    05           18         503.0
12  Utah                Ban_Arrivals_Few    05           19        1076.0
13  Utah                Ban_Arrivals_Few    05           20         987.0
14  Utah                Ban_Arrivals_Few    05           21        1154.0
15  Utah                Ban_Arrivals_Few    05           22        1405.0
16  Utah                Ban_Arrivals_Few    06           23        2269.0
17  Utah                Ban_Arrivals_Few    06           24        2247.0
18  Utah                Ban_Arrivals_Few    06           25        3149.0
19  Utah                Ban_Arrivals_Few    06           26        3638.0
20  Utah                Ban_Arrivals_Few    06           27        1117.0
21  Utah                Ban_Arrivals_Few    07           27        2735.0
22  Utah                Ban_Arrivals_Few    07           28        4532.0
23  Utah                Ban_Arrivals_Few    07           29        4633.0
24  Utah                Ban_Arrivals_Few    07           30        3856.0
25  Utah                Ban_Arrivals_Few    07           31        2223.0
26  Utah                Ban_Arrivals_Few    08           31         979.0
27  Utah                Ban_Arrivals_Few    08           32        2952.0
28  Utah                Ban_Arrivals_Few    08           33        2525.0
29  Utah                Ban_Arrivals_Few    08           34        2463.0
30  Utah                Ban_Arrivals_Few    08           35        2739.0
31  Utah                Ban_Arrivals_Few    08           36         253.0
32  Utah                Ban_Arrivals_Few    09           36        2553.0
33  Utah                Ban_Arrivals_Few    09           37        3215.0
34  Utah                Ban_Arrivals_Few    09           38        5897.0
35  Utah                Ban_Arrivals_Few    09           39        6843.0
36  Utah                Ban_Arrivals_Few    09           40        2427.0
37  Utah                Ban_Arrivals_Few    10           40        4576.0
38  Utah                Ban_Arrivals_Few    10           41        8226.0
39  Utah                Ban_Arrivals_Few    10           42        8550.0
40  Utah                Ban_Arrivals_Few    10           43       10488.0
41  Utah                Ban_Arrivals_Few    10           44        9774.0
42  Utah                Ban_Arrivals_Few    11           44        1854.0
43  Utah                Ban_Arrivals_Few    11           45       16111.0
44  Utah                Ban_Arrivals_Few    11           46       21187.0
45  Utah                Ban_Arrivals_Few    11           47       23368.0
46  Utah                Ban_Arrivals_Few    11           48       16633.0
47  Utah                Ban_Arrivals_Few    11           49        1897.0

In [60]:
df_Wyoming = df_analysis_InternationalRestrictions[df_analysis_InternationalRestrictions['State'] == "Wyoming"]
df_Wyoming= df_Wyoming[[
    'Country',
    'State',
    'InternationalRestrictionsDetail',
    'Daily_New_Cases',
    'Month',
    'Week_Number'
]]
df_Wyoming.groupby(['State', 'InternationalRestrictionsDetail', 'Month', 'Week_Number'])['Daily_New_Cases'].sum().reset_index().rename(columns= {'Daily_New_Cases':'Weekly_Cases'}).sort_values(by=['Month', 'Week_Number'], ascending = True)

      State InternationalRestrictionsDetail Month  Week_Number  Weekly_Cases
0   Wyoming                Ban_Arrivals_Few    03            9           0.0
1   Wyoming                Ban_Arrivals_Few    03           10           0.0
2   Wyoming                Ban_Arrivals_Few    03           11           2.0
3   Wyoming                Ban_Arrivals_Few    03           12          24.0
4   Wyoming                Ban_Arrivals_Few    03           13          60.0
5   Wyoming                Ban_Arrivals_Few    03           14          23.0
6   Wyoming                Ban_Arrivals_Few    04           14          88.0
7   Wyoming                Ban_Arrivals_Few    04           15          73.0
8   Wyoming                Ban_Arrivals_Few    04           16          43.0
9   Wyoming                Ban_Arrivals_Few    04           17         189.0
10  Wyoming                Ban_Arrivals_Few    04           18          57.0
11  Wyoming                Ban_Arrivals_Few    05           18          27.0
12  Wyoming                Ban_Arrivals_Few    05           19          76.0
13  Wyoming                Ban_Arrivals_Few    05           20          92.0
14  Wyoming                Ban_Arrivals_Few    05           21          84.0
15  Wyoming                Ban_Arrivals_Few    05           22          65.0
16  Wyoming                Ban_Arrivals_Few    06           23          44.0
17  Wyoming                Ban_Arrivals_Few    06           24         113.0
18  Wyoming                Ban_Arrivals_Few    06           25         137.0
19  Wyoming                Ban_Arrivals_Few    06           26         220.0
20  Wyoming                Ban_Arrivals_Few    06           27          70.0
21  Wyoming                Ban_Arrivals_Few    07           27         147.0
22  Wyoming                Ban_Arrivals_Few    07           28         228.0
23  Wyoming                Ban_Arrivals_Few    07           29         264.0
24  Wyoming                Ban_Arrivals_Few    07           30         349.0
25  Wyoming                Ban_Arrivals_Few    07           31         251.0
26  Wyoming                Ban_Arrivals_Few    08           31          82.0
27  Wyoming                Ban_Arrivals_Few    08           32         242.0
28  Wyoming                Ban_Arrivals_Few    08           33         236.0
29  Wyoming                Ban_Arrivals_Few    08           34         292.0
30  Wyoming                Ban_Arrivals_Few    08           35         251.0
31  Wyoming                Ban_Arrivals_Few    08           36          21.0
32  Wyoming                Ban_Arrivals_Few    09           36         182.0
33  Wyoming                Ban_Arrivals_Few    09           37         314.0
34  Wyoming                Ban_Arrivals_Few    09           38         526.0
35  Wyoming                Ban_Arrivals_Few    09           39         761.0
36  Wyoming                Ban_Arrivals_Few    09           40         315.0
37  Wyoming                Ban_Arrivals_Few    10           40         556.0
38  Wyoming                Ban_Arrivals_Few    10           41        1107.0
39  Wyoming                Ban_Arrivals_Few    10           42        1414.0
40  Wyoming                Ban_Arrivals_Few    10           43        2016.0
41  Wyoming                Ban_Arrivals_Few    10           44        2257.0
42  Wyoming                Ban_Arrivals_Few    11           44         425.0
43  Wyoming                Ban_Arrivals_Few    11           45        3587.0
44  Wyoming                Ban_Arrivals_Few    11           46        5184.0
45  Wyoming                Ban_Arrivals_Few    11           47        5675.0
46  Wyoming                Ban_Arrivals_Few    11           48        4320.0
47  Wyoming                Ban_Arrivals_Few    11           49         816.0

In [61]:
df_Hawaii = df_analysis_InternationalRestrictions[df_analysis_InternationalRestrictions['State'] == "Hawaii"]
df_Hawaii= df_Hawaii[[
    'Country',
    'State',
    'InternationalRestrictionsDetail',
    'Daily_New_Cases',
    'Month',
    'Week_Number'
]]
df_Hawaii.groupby(['State', 'InternationalRestrictionsDetail', 'Month', 'Week_Number'])['Daily_New_Cases'].sum().reset_index().rename(columns= {'Daily_New_Cases':'Weekly_Cases'}).sort_values(by=['Month', 'Week_Number'], ascending = True)

     State InternationalRestrictionsDetail Month  Week_Number  Weekly_Cases
0   Hawaii                Ban_Arrivals_Few    03            9           0.0
1   Hawaii                Ban_Arrivals_Few    03           10           1.0
2   Hawaii                Ban_Arrivals_Few    03           11           5.0
3   Hawaii                Ban_Arrivals_Few    03           12          47.0
4   Hawaii                Ban_Arrivals_Few    03           13          96.0
5   Hawaii                Ban_Arrivals_Few    03           14          55.0
6   Hawaii                Ban_Arrivals_Few    04           14         167.0
7   Hawaii                Ban_Arrivals_Few    04           15         128.0
8   Hawaii                Ban_Arrivals_Few    04           16          81.0
9   Hawaii                Ban_Arrivals_Few    04           17          26.0
10  Hawaii                Ban_Arrivals_Few    04           18          12.0
11  Hawaii                Ban_Arrivals_Few    05           18           2.0
12  Hawaii                Ban_Arrivals_Few    05           19          12.0
13  Hawaii                Ban_Arrivals_Few    05           20           8.0
14  Hawaii                Ban_Arrivals_Few    05           21           3.0
15  Hawaii                Ban_Arrivals_Few    05           22           9.0
16  Hawaii                Ban_Arrivals_Few    06           23          23.0
17  Hawaii                Ban_Arrivals_Few    06           24          53.0
18  Hawaii                Ban_Arrivals_Few    06           25          86.0
19  Hawaii                Ban_Arrivals_Few    06           26          85.0
20  Hawaii                Ban_Arrivals_Few    06           27          18.0
21  Hawaii                Ban_Arrivals_Few    07           27         106.0
22  Hawaii                Ban_Arrivals_Few    07           28         197.0
23  Hawaii                Ban_Arrivals_Few    07           29         161.0
24  Hawaii                Ban_Arrivals_Few    07           30         302.0
25  Hawaii                Ban_Arrivals_Few    07           31         428.0
26  Hawaii                Ban_Arrivals_Few    08           31         131.0
27  Hawaii                Ban_Arrivals_Few    08           32        1256.0
28  Hawaii                Ban_Arrivals_Few    08           33        1544.0
29  Hawaii                Ban_Arrivals_Few    08           34        1558.0
30  Hawaii                Ban_Arrivals_Few    08           35        1739.0
31  Hawaii                Ban_Arrivals_Few    08           36         133.0
32  Hawaii                Ban_Arrivals_Few    09           36        1383.0
33  Hawaii                Ban_Arrivals_Few    09           37         979.0
34  Hawaii                Ban_Arrivals_Few    09           38         728.0
35  Hawaii                Ban_Arrivals_Few    09           39         741.0
36  Hawaii                Ban_Arrivals_Few    09           40         294.0
37  Hawaii                Ban_Arrivals_Few    10           40         394.0
38  Hawaii                Ban_Arrivals_Few    10           41         675.0
39  Hawaii                Ban_Arrivals_Few    10           42         559.0
40  Hawaii                Ban_Arrivals_Few    10           43         652.0
41  Hawaii                Ban_Arrivals_Few    10           44         407.0
42  Hawaii                Ban_Arrivals_Few    11           44          83.0
43  Hawaii                Ban_Arrivals_Few    11           45         812.0
44  Hawaii                Ban_Arrivals_Few    11           46         580.0
45  Hawaii                Ban_Arrivals_Few    11           47         724.0
46  Hawaii                Ban_Arrivals_Few    11           48         655.0
47  Hawaii                Ban_Arrivals_Few    11           49          85.0

In [62]:
df_Maine = df_analysis_InternationalRestrictions[df_analysis_InternationalRestrictions['State'] == "Maine"]
df_Maine= df_Maine[[
    'Country',
    'State',
    'InternationalRestrictionsDetail',
    'Daily_New_Cases',
    'Month',
    'Week_Number'
]]
df_Maine.groupby(['State', 'InternationalRestrictionsDetail', 'Month', 'Week_Number'])['Daily_New_Cases'].sum().reset_index().rename(columns= {'Daily_New_Cases':'Weekly_Cases'}).sort_values(by=['Month', 'Week_Number'], ascending = True)

    State InternationalRestrictionsDetail Month  Week_Number  Weekly_Cases
0   Maine                Ban_Arrivals_Few    03            9           0.0
1   Maine                Ban_Arrivals_Few    03           10           0.0
2   Maine                Ban_Arrivals_Few    03           11           2.0
3   Maine                Ban_Arrivals_Few    03           12          87.0
4   Maine                Ban_Arrivals_Few    03           13         164.0
5   Maine                Ban_Arrivals_Few    03           14          50.0
6   Maine                Ban_Arrivals_Few    04           14         167.0
7   Maine                Ban_Arrivals_Few    04           15         163.0
8   Maine                Ban_Arrivals_Few    04           16         234.0
9   Maine                Ban_Arrivals_Few    04           17         148.0
10  Maine                Ban_Arrivals_Few    04           18          80.0
11  Maine                Ban_Arrivals_Few    05           18          90.0
12  Maine                Ban_Arrivals_Few    05           19         251.0
13  Maine                Ban_Arrivals_Few    05           20         251.0
14  Maine                Ban_Arrivals_Few    05           21         368.0
15  Maine                Ban_Arrivals_Few    05           22         270.0
16  Maine                Ban_Arrivals_Few    06           23         245.0
17  Maine                Ban_Arrivals_Few    06           24         223.0
18  Maine                Ban_Arrivals_Few    06           25         164.0
19  Maine                Ban_Arrivals_Few    06           26         234.0
20  Maine                Ban_Arrivals_Few    06           27          62.0
21  Maine                Ban_Arrivals_Few    07           27         162.0
22  Maine                Ban_Arrivals_Few    07           28         124.0
23  Maine                Ban_Arrivals_Few    07           29         148.0
24  Maine                Ban_Arrivals_Few    07           30         127.0
25  Maine                Ban_Arrivals_Few    07           31          98.0
26  Maine                Ban_Arrivals_Few    08           31          46.0
27  Maine                Ban_Arrivals_Few    08           32          86.0
28  Maine                Ban_Arrivals_Few    08           33         124.0
29  Maine                Ban_Arrivals_Few    08           34         168.0
30  Maine                Ban_Arrivals_Few    08           35         178.0
31  Maine                Ban_Arrivals_Few    08           36          15.0
32  Maine                Ban_Arrivals_Few    09           36         154.0
33  Maine                Ban_Arrivals_Few    09           37         180.0
34  Maine                Ban_Arrivals_Few    09           38         214.0
35  Maine                Ban_Arrivals_Few    09           39         210.0
36  Maine                Ban_Arrivals_Few    09           40         102.0
37  Maine                Ban_Arrivals_Few    10           40         130.0
38  Maine                Ban_Arrivals_Few    10           41         201.0
39  Maine                Ban_Arrivals_Few    10           42         217.0
40  Maine                Ban_Arrivals_Few    10           43         262.0
41  Maine                Ban_Arrivals_Few    10           44         463.0
42  Maine                Ban_Arrivals_Few    11           44          49.0
43  Maine                Ban_Arrivals_Few    11           45         982.0
44  Maine                Ban_Arrivals_Few    11           46        1251.0
45  Maine                Ban_Arrivals_Few    11           47        1415.0
46  Maine                Ban_Arrivals_Few    11           48        1149.0
47  Maine                Ban_Arrivals_Few    11           49         249.0

In [63]:
df_Vermont = df_analysis_InternationalRestrictions[df_analysis_InternationalRestrictions['State'] == "Vermont"]
df_Vermont= df_Vermont[[
    'Country',
    'State',
    'InternationalRestrictionsDetail',
    'Daily_New_Cases',
    'Month',
    'Week_Number'
]]
df_Vermont.groupby(['State', 'InternationalRestrictionsDetail', 'Month', 'Week_Number'])['Daily_New_Cases'].sum().reset_index().rename(columns= {'Daily_New_Cases':'Weekly_Cases'}).sort_values(by=['Month', 'Week_Number'], ascending = True)

      State InternationalRestrictionsDetail Month  Week_Number  Weekly_Cases
0   Vermont                Ban_Arrivals_Few    03            9           0.0
1   Vermont                Ban_Arrivals_Few    03           10           1.0
2   Vermont                Ban_Arrivals_Few    03           11           4.0
3   Vermont                Ban_Arrivals_Few    03           12          47.0
4   Vermont                Ban_Arrivals_Few    03           13         183.0
5   Vermont                Ban_Arrivals_Few    03           14          58.0
6   Vermont                Ban_Arrivals_Few    04           14         219.0
7   Vermont                Ban_Arrivals_Few    04           15         215.0
8   Vermont                Ban_Arrivals_Few    04           16          86.0
9   Vermont                Ban_Arrivals_Few    04           17          38.0
10  Vermont                Ban_Arrivals_Few    04           18          15.0
11  Vermont                Ban_Arrivals_Few    05           18          31.0
12  Vermont                Ban_Arrivals_Few    05           19          30.0
13  Vermont                Ban_Arrivals_Few    05           20          13.0
14  Vermont                Ban_Arrivals_Few    05           21          16.0
15  Vermont                Ban_Arrivals_Few    05           22          25.0
16  Vermont                Ban_Arrivals_Few    06           23          82.0
17  Vermont                Ban_Arrivals_Few    06           24          64.0
18  Vermont                Ban_Arrivals_Few    06           25          32.0
19  Vermont                Ban_Arrivals_Few    06           26          43.0
20  Vermont                Ban_Arrivals_Few    06           27           6.0
21  Vermont                Ban_Arrivals_Few    07           27          41.0
22  Vermont                Ban_Arrivals_Few    07           28          47.0
23  Vermont                Ban_Arrivals_Few    07           29          54.0
24  Vermont                Ban_Arrivals_Few    07           30          50.0
25  Vermont                Ban_Arrivals_Few    07           31          14.0
26  Vermont                Ban_Arrivals_Few    08           31          12.0
27  Vermont                Ban_Arrivals_Few    08           32          33.0
28  Vermont                Ban_Arrivals_Few    08           33          56.0
29  Vermont                Ban_Arrivals_Few    08           34          42.0
30  Vermont                Ban_Arrivals_Few    08           35          59.0
31  Vermont                Ban_Arrivals_Few    08           36           8.0
32  Vermont                Ban_Arrivals_Few    09           36          24.0
33  Vermont                Ban_Arrivals_Few    09           37          36.0
34  Vermont                Ban_Arrivals_Few    09           38          31.0
35  Vermont                Ban_Arrivals_Few    09           39          27.0
36  Vermont                Ban_Arrivals_Few    09           40          10.0
37  Vermont                Ban_Arrivals_Few    10           40          33.0
38  Vermont                Ban_Arrivals_Few    10           41          83.0
39  Vermont                Ban_Arrivals_Few    10           42          69.0
40  Vermont                Ban_Arrivals_Few    10           43         136.0
41  Vermont                Ban_Arrivals_Few    10           44         106.0
42  Vermont                Ban_Arrivals_Few    11           44          17.0
43  Vermont                Ban_Arrivals_Few    11           45         196.0
44  Vermont                Ban_Arrivals_Few    11           46         497.0
45  Vermont                Ban_Arrivals_Few    11           47         740.0
46  Vermont                Ban_Arrivals_Few    11           48         471.0
47  Vermont                Ban_Arrivals_Few    11           49          72.0